
  CREATE TABLE "SCOTT"."APPROVAL_PATH" 
   (	"DOCNO" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(5 BYTE), 
	"GUBUN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SCOTT"."APPROVAL_PATH"."DOCNO" IS '문서번호';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL_PATH"."USERID" IS '사용자ID';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL_PATH"."USERNAME" IS '사용자이름';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL_PATH"."STATUS" IS '문서상태';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL_PATH"."GUBUN" IS '결재구분';
 
