
  CREATE TABLE "SCOTT"."APPROVAL" 
   (	"DOCNO" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"INID" VARCHAR2(20 BYTE), 
	"INDT" VARCHAR2(20 BYTE), 
	"DEPTNAME" VARCHAR2(20 BYTE), 
	"TEAMNAME" VARCHAR2(20 BYTE), 
	"TYPEGUBUN" VARCHAR2(5 BYTE), 
	"STARTDT" VARCHAR2(20 BYTE), 
	"ENDDT" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"HOLIDAY" VARCHAR2(20 BYTE), 
	 CONSTRAINT "APPROVAL_PK" PRIMARY KEY ("DOCNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SCOTT"."APPROVAL"."DOCNO" IS '문서번호';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."NAME" IS '작성자';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."INID" IS '작성자ID';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."INDT" IS '작성일시';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."DEPTNAME" IS '부서명';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."TEAMNAME" IS '팀명';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."TYPEGUBUN" IS '문서양식';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."STARTDT" IS '시작일시';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."ENDDT" IS '종료일시';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."TITLE" IS '제목';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."CONTENT" IS '내용';
 
   COMMENT ON COLUMN "SCOTT"."APPROVAL"."HOLIDAY" IS '휴가구분';
 
