  CREATE TABLE "SCOTT"."BOARD" 
   (   "NUM" NUMBER(*,0) NOT NULL ENABLE, 
   "BOARDID" VARCHAR2(1 BYTE) DEFAULT '1', 
   "WRITER" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
   "EMAIL" VARCHAR2(30 BYTE), 
   "SUBJECT" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
   "PASSWD" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
   "REG_DATE" DATE NOT NULL ENABLE, 
   "READCOUNT" NUMBER(*,0) DEFAULT 0, 
   "REF" NUMBER(*,0) NOT NULL ENABLE, 
   "RE_STEP" NUMBER(*,0) NOT NULL ENABLE, 
   "RE_LEVEL" NUMBER(*,0) NOT NULL ENABLE, 
   "CONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
   "IP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "FILENAME" VARCHAR2(30 BYTE), 
   "FILESIZE" NUMBER(*,0), 
    PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;